### ISSUE TITLE
Use basicConfig() if logging.conf is not found

### ISSUE THREAD

**Issue by siso** [boxidau/rax-autoscaler#46]
If logging.conf is not found, then call `basicConfig()` to ensure that at least one handler is available.

```
vagrant@default-ubuntu-1404:~$ autoscale 
Traceback (most recent call last):
  File "/usr/local/bin/autoscale", line 9, in <module>
    load_entry_point('RAX-AutoScaler==0.2.1', 'console_scripts', 'autoscale')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2088, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "build/bdist.linux-x86_64/egg/raxas/autoscale.py", line 38, in <module>
  File "/usr/lib/python2.7/logging/config.py", line 77, in fileConfig
    formatters = _create_formatters(cp)
  File "/usr/lib/python2.7/logging/config.py", line 113, in _create_formatters
    flist = cp.get("formatters", "keys")
  File "/usr/lib/python2.7/ConfigParser.py", line 607, in get
    raise NoSectionError(section)
ConfigParser.NoSectionError: No section: 'formatters'
```

**Comment by siso** [comment]
I still get this error if logging.conf is not found, can you please check it?

**Comment by sthapa-ping** [comment]
re-checked, it works for me without logging.conf

**Comment by sthapa-ping** [comment]
I have been committing changes to devel branch, I will push my changes to release branch ASAP.
