### ISSUE TITLE
Crashed on no data

### ISSUE THREAD

**Issue by boxidau** [boxidau/rax-autoscaler#6]
Traceback (most recent call last):
  File "/root/rax-autoscaler/autoscale.py", line 142, in <module>
    autoscale(args['as_group'], config, args['cluster'])
  File "/root/rax-autoscaler/autoscale.py", line 97, in autoscale
    if len(data) == 0:
UnboundLocalError: local variable 'data' referenced before assignment

**Comment by boxidau** [comment]
len(data) changed for len(results), issue fixed
